### ISSUE TITLE
whitelist-system

### ISSUE THREAD

**Issue by shazron** [jessemonroy650/top-phonegap-mistakes#5]
Thanks for the write-up!

re: https://github.com/jessemonroy650/top-phonegap-mistakes/blob/master/whitelist-system.md

With the next Tools release 5.4.0 (vote ongoing), `<access>` tags are converted to the appropriate ATS entries.
commit: https://github.com/apache/cordova-lib/commit/0c3614e2fff6f3579a9220611ad439abde9abde1

There is a proposal to scrap the (cordova) whitelist system on cordova-ios 4.0 because of the complexity:
PR:
https://github.com/cordova/cordova-discuss/pull/27

View:
https://github.com/shazron/cordova-discuss/blob/ios-remove-whitelist/proposals/ios-whitelist-removal.md

Input appreciated.

**Comment by shazron** [comment]
Thread on the dev@cordova.apache.org mailing list: http://callback-dev.markmail.org/thread/6de6jgkdraltqasn

**Comment by jessemonroy650** [comment]
Thanks. I'll be following up.
